
server:
  port: 8769
spring:
  application:
    name: myZuul
  cloud:
          consul:
            host: localhost
            port: 8500
            enabled: true
            discovery:
              enabled: true
              register: true
              prefer-ip-address: true
zuul:
  routes:
    api-a:
      path: /myWeb/**
      serviceId: mySpringbootMybatis